# Generated by Django 3.0.2 on 2021-06-01 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='forgot', max_length=30)),
                ('codeForces_username', models.CharField(max_length=30)),
                ('year', models.IntegerField(help_text='Year of Admission')),
                ('rating', models.IntegerField(default=800)),
                ('sloved_problems', models.ManyToManyField(blank=True, related_name='UserSolved', to='index.Problem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
