# Generated by Django 3.0.2 on 2021-06-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='not_sloved_problems',
            field=models.ManyToManyField(blank=True, related_name='UserNotSolved', to='index.Problem'),
        ),
    ]
