# Generated by Django 3.0.2 on 2021-06-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210614_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-rating', '-sloved_problems_count']},
        ),
    ]
