# Generated by Django 3.1.2 on 2021-05-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0004_auto_20210521_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestID', models.IntegerField()),
                ('index', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('problems', models.ManyToManyField(blank=True, related_name='Problme', to='index.Problem')),
            ],
            options={
                'unique_together': {('contestID', 'index')},
            },
        ),
    ]
