# Generated by Django 3.0.2 on 2021-06-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20210606_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contestID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='contest',
            unique_together=set(),
        ),
    ]
