# Generated by Django 3.0.2 on 2021-06-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20210606_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='empty',
            field=models.IntegerField(default=0),
        ),
    ]
