# Generated by Django 3.1.2 on 2021-06-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='color',
        ),
    ]
