# Generated by Django 3.0.2 on 2021-05-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210515_1331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('contestID', 'index')},
        ),
    ]
