# Generated by Django 3.0.2 on 2021-05-21 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210521_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_title',
        ),
    ]
