# Generated by Django 3.0.2 on 2021-05-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        ('users', '0002_userprofile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-rating']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.IntegerField(default=800),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sloved_problems',
            field=models.ManyToManyField(blank=True, related_name='UserSolved', to='index.Problem'),
        ),
    ]
